### ISSUE TITLE
Permission to use this repo URL 

### ISSUE THREAD

**Issue by dipakkr** [Prukalpa/Women-Engineers-India-Ultimate-List#8]
Hi @Prukalpa, 

We have built a list of resources for students similar to the repo. I found your content useful. 
If you agree, I would like to add your repo URL to our resource list. 

Github Repo URL -> https://github.com/dipakkr/A-to-Z-Resources-for-Students

Thanks!!

**Comment by Prukalpa** [comment]
Hi @dipakkr - Go ahead!
